---
language: ruby
sudo: true
install:
  - cd $TRAVIS_BUILD_DIR
  - ls
  - sudo python puppet/install.py

env:
  - PUPPET_GEM_VERSION="~> 3.4.3"
  - PUPPET_GEM_VERSION="~> 3.8.5"
rvm:
  - 1.9.3
  - 2.3

script:    
  

matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.8.5"
    - rvm: 2.3
      env: PUPPET_GEM_VERSION="~> 3.4.3"

