---
language: ruby
bundler_args: --without rake
os:
  - linux
dist: trusty
sudo: true
env:
  - PUPPET_GEM_VERSION="~> 3.4.3"
  - PUPPET_GEM_VERSION="~> 3.8.5"
rvm:
  - 1.9.3
  - 2.3

install:
  - export PATH=$PATH:$GEM_HOME/bin
  - cd $TRAVIS_BUILD_DIR
  - sudo python puppet/install.py --verbose
  - echo $PATH
  - librarian-puppet

script:
  - cd $TRAVIS_BUILD_DIR
  - sudo find / -name librarian*
  - bash puppet/.travis.run_tests.bash

matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.8.5"
    - rvm: 2.3
      env: PUPPET_GEM_VERSION="~> 3.4.3"
