---
language: ruby
bundler_args: --without rake
os:
  - linux
dist: trusty
sudo: true
install:
  - cd $TRAVIS_BUILD_DIR
  - sudo python puppet/install.py --verbose

env:
  - PUPPET_GEM_VERSION="~> 3.4.3"
  - PUPPET_GEM_VERSION="~> 3.8.5"
rvm:
  - 1.9.3
  - 2.3

script:
  - cd $TRAVIS_BUILD_DIR
  - bash puppet/.travis_run_tests.bash

matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.8.5"
    - rvm: 2.3
      env: PUPPET_GEM_VERSION="~> 3.4.3"
