---
language: ruby
bundler_args: --without rake
os:
  - linux
dist: trusty
sudo: true
env:
  - PUPPET_GEM_VERSION="~> 3.4.3"
  - PUPPET_GEM_VERSION="~> 3.8.5"
rvm:
  - 1.9.3
  - 2.3

script:
  - cd $TRAVIS_BUILD_DIR
  - export PATH=$PATH:$GEM_HOME/bin
  - sudo python puppet/install.py --verbose
  # For some reason travis can not find librarian-puppet so rewrite commands from install.py
  - cd puppet
  - librarian-puppet install
  - sudo cp -a /tmp/repo/puppet/* /etc/puppet
  - puppet apply /etc/puppet/manifests/site.pp puppet apply /etc/puppet/manifests/site.pp
  - bash puppet/.travis.run_tests.bash

matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.8.5"
    - rvm: 2.3
      env: PUPPET_GEM_VERSION="~> 3.4.3"
