forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-stdlib', '4.13.1'
mod 'puppetlabs-apt', '2.3.0'
mod 'gdsoperations-aptly',
  :git => 'git://github.com/gds-operations/puppet-aptly.git',
  :ref => 'v0.7.0'
mod 'golja-gnupg', '1.2.3'
mod 'puppetlabs-apache', '1.10.0'
